import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import NetworkErrorProvider from "../components/NetworkErrorProvider";

const sarabun = Sarabun({
  variable: "--font-sarabun",
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sarabun.variable}>
        <NetworkErrorProvider>
          {children}
        </NetworkErrorProvider>
      </body>
    </html>
  );
}
